add_lunch_combo aosip_angler-userdebug
add_lunch_combo aosip_marlin-userdebug
add_lunch_combo aosip_oneplus2-userdebug
add_lunch_combo aosip_oneplus3-userdebug
add_lunch_combo aosip_cheeseburger-userdebug
